version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - internal/pr/repository/postgres/sqlc
    - internal/pr/usecase/mocks

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - revive
    - gocyclo
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    severity: warning
    rules:
      - name: indent-error-flow
      - name: blank-imports
      - name: if-return
      - name: var-naming
      - name: exported
        disabled: true
      - name: error-return
      - name: unexported-return

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude:
    - "error return value not checked.*(Close|Write|Fprintf)"