// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository (interfaces: StatsRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_stats_repository.go -package=mocks github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository StatsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsRepository is a mock of StatsRepository interface.
type MockStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepositoryMockRecorder
	isgomock struct{}
}

// MockStatsRepositoryMockRecorder is the mock recorder for MockStatsRepository.
type MockStatsRepositoryMockRecorder struct {
	mock *MockStatsRepository
}

// NewMockStatsRepository creates a new mock instance.
func NewMockStatsRepository(ctrl *gomock.Controller) *MockStatsRepository {
	mock := &MockStatsRepository{ctrl: ctrl}
	mock.recorder = &MockStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepository) EXPECT() *MockStatsRepositoryMockRecorder {
	return m.recorder
}

// GetPRStats mocks base method.
func (m *MockStatsRepository) GetPRStats(ctx context.Context) (*domain.PRStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRStats", ctx)
	ret0, _ := ret[0].(*domain.PRStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRStats indicates an expected call of GetPRStats.
func (mr *MockStatsRepositoryMockRecorder) GetPRStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRStats", reflect.TypeOf((*MockStatsRepository)(nil).GetPRStats), ctx)
}

// GetReviewerWorkload mocks base method.
func (m *MockStatsRepository) GetReviewerWorkload(ctx context.Context) ([]domain.ReviewerWorkload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewerWorkload", ctx)
	ret0, _ := ret[0].([]domain.ReviewerWorkload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewerWorkload indicates an expected call of GetReviewerWorkload.
func (mr *MockStatsRepositoryMockRecorder) GetReviewerWorkload(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewerWorkload", reflect.TypeOf((*MockStatsRepository)(nil).GetReviewerWorkload), ctx)
}

// GetUserAssignmentStats mocks base method.
func (m *MockStatsRepository) GetUserAssignmentStats(ctx context.Context) ([]domain.UserAssignmentStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAssignmentStats", ctx)
	ret0, _ := ret[0].([]domain.UserAssignmentStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAssignmentStats indicates an expected call of GetUserAssignmentStats.
func (mr *MockStatsRepositoryMockRecorder) GetUserAssignmentStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAssignmentStats", reflect.TypeOf((*MockStatsRepository)(nil).GetUserAssignmentStats), ctx)
}
