// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository (interfaces: UnitOfWork)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_unit_of_work.go -package=mocks github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository UnitOfWork
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// PullRequests mocks base method.
func (m *MockUnitOfWork) PullRequests() repository.PRRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequests")
	ret0, _ := ret[0].(repository.PRRepository)
	return ret0
}

// PullRequests indicates an expected call of PullRequests.
func (mr *MockUnitOfWorkMockRecorder) PullRequests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequests", reflect.TypeOf((*MockUnitOfWork)(nil).PullRequests))
}

// Reviewers mocks base method.
func (m *MockUnitOfWork) Reviewers() repository.ReviewerRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reviewers")
	ret0, _ := ret[0].(repository.ReviewerRepository)
	return ret0
}

// Reviewers indicates an expected call of Reviewers.
func (mr *MockUnitOfWorkMockRecorder) Reviewers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reviewers", reflect.TypeOf((*MockUnitOfWork)(nil).Reviewers))
}

// Stats mocks base method.
func (m *MockUnitOfWork) Stats() repository.StatsRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats")
	ret0, _ := ret[0].(repository.StatsRepository)
	return ret0
}

// Stats indicates an expected call of Stats.
func (mr *MockUnitOfWorkMockRecorder) Stats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockUnitOfWork)(nil).Stats))
}

// Teams mocks base method.
func (m *MockUnitOfWork) Teams() repository.TeamRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Teams")
	ret0, _ := ret[0].(repository.TeamRepository)
	return ret0
}

// Teams indicates an expected call of Teams.
func (mr *MockUnitOfWorkMockRecorder) Teams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Teams", reflect.TypeOf((*MockUnitOfWork)(nil).Teams))
}

// Users mocks base method.
func (m *MockUnitOfWork) Users() repository.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(repository.UserRepository)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockUnitOfWorkMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockUnitOfWork)(nil).Users))
}

// WithinTransaction mocks base method.
func (m *MockUnitOfWork) WithinTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockUnitOfWorkMockRecorder) WithinTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockUnitOfWork)(nil).WithinTransaction), ctx, fn)
}
