// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository (interfaces: ReviewerRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_reviewer_repository.go -package=mocks github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository ReviewerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReviewerRepository is a mock of ReviewerRepository interface.
type MockReviewerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewerRepositoryMockRecorder
	isgomock struct{}
}

// MockReviewerRepositoryMockRecorder is the mock recorder for MockReviewerRepository.
type MockReviewerRepositoryMockRecorder struct {
	mock *MockReviewerRepository
}

// NewMockReviewerRepository creates a new mock instance.
func NewMockReviewerRepository(ctrl *gomock.Controller) *MockReviewerRepository {
	mock := &MockReviewerRepository{ctrl: ctrl}
	mock.recorder = &MockReviewerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewerRepository) EXPECT() *MockReviewerRepositoryMockRecorder {
	return m.recorder
}

// AssignReviewer mocks base method.
func (m *MockReviewerRepository) AssignReviewer(ctx context.Context, prID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignReviewer", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignReviewer indicates an expected call of AssignReviewer.
func (mr *MockReviewerRepositoryMockRecorder) AssignReviewer(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignReviewer", reflect.TypeOf((*MockReviewerRepository)(nil).AssignReviewer), ctx, prID, reviewerID)
}

// FindCandidatesForNewPR mocks base method.
func (m *MockReviewerRepository) FindCandidatesForNewPR(ctx context.Context, teamName, authorID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCandidatesForNewPR", ctx, teamName, authorID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCandidatesForNewPR indicates an expected call of FindCandidatesForNewPR.
func (mr *MockReviewerRepositoryMockRecorder) FindCandidatesForNewPR(ctx, teamName, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCandidatesForNewPR", reflect.TypeOf((*MockReviewerRepository)(nil).FindCandidatesForNewPR), ctx, teamName, authorID)
}

// FindCandidatesForReassignment mocks base method.
func (m *MockReviewerRepository) FindCandidatesForReassignment(ctx context.Context, teamName, authorID, prID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCandidatesForReassignment", ctx, teamName, authorID, prID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCandidatesForReassignment indicates an expected call of FindCandidatesForReassignment.
func (mr *MockReviewerRepositoryMockRecorder) FindCandidatesForReassignment(ctx, teamName, authorID, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCandidatesForReassignment", reflect.TypeOf((*MockReviewerRepository)(nil).FindCandidatesForReassignment), ctx, teamName, authorID, prID)
}

// GetAssignedReviewers mocks base method.
func (m *MockReviewerRepository) GetAssignedReviewers(ctx context.Context, prID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignedReviewers", ctx, prID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignedReviewers indicates an expected call of GetAssignedReviewers.
func (mr *MockReviewerRepositoryMockRecorder) GetAssignedReviewers(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignedReviewers", reflect.TypeOf((*MockReviewerRepository)(nil).GetAssignedReviewers), ctx, prID)
}

// IsReviewerAssigned mocks base method.
func (m *MockReviewerRepository) IsReviewerAssigned(ctx context.Context, prID, reviewerID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReviewerAssigned", ctx, prID, reviewerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReviewerAssigned indicates an expected call of IsReviewerAssigned.
func (mr *MockReviewerRepositoryMockRecorder) IsReviewerAssigned(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReviewerAssigned", reflect.TypeOf((*MockReviewerRepository)(nil).IsReviewerAssigned), ctx, prID, reviewerID)
}

// ListPRsByReviewer mocks base method.
func (m *MockReviewerRepository) ListPRsByReviewer(ctx context.Context, reviewerID string) ([]domain.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPRsByReviewer", ctx, reviewerID)
	ret0, _ := ret[0].([]domain.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPRsByReviewer indicates an expected call of ListPRsByReviewer.
func (mr *MockReviewerRepositoryMockRecorder) ListPRsByReviewer(ctx, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPRsByReviewer", reflect.TypeOf((*MockReviewerRepository)(nil).ListPRsByReviewer), ctx, reviewerID)
}

// ReplaceReviewer mocks base method.
func (m *MockReviewerRepository) ReplaceReviewer(ctx context.Context, prID, oldReviewerID, newReviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceReviewer", ctx, prID, oldReviewerID, newReviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceReviewer indicates an expected call of ReplaceReviewer.
func (mr *MockReviewerRepositoryMockRecorder) ReplaceReviewer(ctx, prID, oldReviewerID, newReviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceReviewer", reflect.TypeOf((*MockReviewerRepository)(nil).ReplaceReviewer), ctx, prID, oldReviewerID, newReviewerID)
}
