// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository (interfaces: PRRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_pr_repository.go -package=mocks github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/usecase/repository PRRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/NutsBalls/Backend-trainee-assignment-autumn-2025/internal/pr/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPRRepository is a mock of PRRepository interface.
type MockPRRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPRRepositoryMockRecorder
	isgomock struct{}
}

// MockPRRepositoryMockRecorder is the mock recorder for MockPRRepository.
type MockPRRepositoryMockRecorder struct {
	mock *MockPRRepository
}

// NewMockPRRepository creates a new mock instance.
func NewMockPRRepository(ctrl *gomock.Controller) *MockPRRepository {
	mock := &MockPRRepository{ctrl: ctrl}
	mock.recorder = &MockPRRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRRepository) EXPECT() *MockPRRepositoryMockRecorder {
	return m.recorder
}

// CreatePR mocks base method.
func (m *MockPRRepository) CreatePR(ctx context.Context, pr *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockPRRepositoryMockRecorder) CreatePR(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockPRRepository)(nil).CreatePR), ctx, pr)
}

// GetPR mocks base method.
func (m *MockPRRepository) GetPR(ctx context.Context, prID string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPR", ctx, prID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPR indicates an expected call of GetPR.
func (mr *MockPRRepositoryMockRecorder) GetPR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPR", reflect.TypeOf((*MockPRRepository)(nil).GetPR), ctx, prID)
}

// GetPRAuthorID mocks base method.
func (m *MockPRRepository) GetPRAuthorID(ctx context.Context, prID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRAuthorID", ctx, prID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRAuthorID indicates an expected call of GetPRAuthorID.
func (mr *MockPRRepositoryMockRecorder) GetPRAuthorID(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRAuthorID", reflect.TypeOf((*MockPRRepository)(nil).GetPRAuthorID), ctx, prID)
}

// GetPRWithReviewers mocks base method.
func (m *MockPRRepository) GetPRWithReviewers(ctx context.Context, prID string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRWithReviewers", ctx, prID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRWithReviewers indicates an expected call of GetPRWithReviewers.
func (mr *MockPRRepositoryMockRecorder) GetPRWithReviewers(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRWithReviewers", reflect.TypeOf((*MockPRRepository)(nil).GetPRWithReviewers), ctx, prID)
}

// MergePR mocks base method.
func (m *MockPRRepository) MergePR(ctx context.Context, prID string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, prID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePR indicates an expected call of MergePR.
func (mr *MockPRRepositoryMockRecorder) MergePR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockPRRepository)(nil).MergePR), ctx, prID)
}

// PRExists mocks base method.
func (m *MockPRRepository) PRExists(ctx context.Context, prID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRExists", ctx, prID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PRExists indicates an expected call of PRExists.
func (mr *MockPRRepositoryMockRecorder) PRExists(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRExists", reflect.TypeOf((*MockPRRepository)(nil).PRExists), ctx, prID)
}
