// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type AssignedReviewer struct {
	PrID       string `json:"pr_id"`
	ReviewerID string `json:"reviewer_id"`
}

type PullRequest struct {
	PullRequestID   string     `json:"pull_request_id"`
	PullRequestName string     `json:"pull_request_name"`
	AuthorID        string     `json:"author_id"`
	Status          string     `json:"status"`
	CreatedAt       time.Time  `json:"created_at"`
	MergedAt        *time.Time `json:"merged_at"`
}

type Team struct {
	TeamName string `json:"team_name"`
}

type User struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	TeamName string `json:"team_name"`
	IsActive bool   `json:"is_active"`
}
