// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_requests.sql

package sqlc

import (
	"context"
)

const createPullRequest = `-- name: CreatePullRequest :one
INSERT INTO pull_requests (pull_request_id, pull_request_name, author_id, status)
VALUES ($1, $2, $3, 'OPEN')
RETURNING pull_request_id, pull_request_name, author_id, status, created_at, merged_at
`

type CreatePullRequestParams struct {
	PullRequestID   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
	AuthorID        string `json:"author_id"`
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, createPullRequest, arg.PullRequestID, arg.PullRequestName, arg.AuthorID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const getPRAuthorId = `-- name: GetPRAuthorId :one
SELECT author_id
FROM pull_requests
WHERE pull_request_id = $1
`

func (q *Queries) GetPRAuthorId(ctx context.Context, pullRequestID string) (string, error) {
	row := q.db.QueryRow(ctx, getPRAuthorId, pullRequestID)
	var author_id string
	err := row.Scan(&author_id)
	return author_id, err
}

const getPullRequest = `-- name: GetPullRequest :one
SELECT pull_request_id, pull_request_name, author_id, status, created_at, merged_at
FROM pull_requests
WHERE pull_request_id = $1
`

func (q *Queries) GetPullRequest(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequest, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const listPullRequestsByReviewer = `-- name: ListPullRequestsByReviewer :many
SELECT pr.pull_request_id, pr.pull_request_name, pr.author_id, pr.status
FROM pull_requests pr
JOIN assigned_reviewers ar ON pr.pull_request_id = ar.pr_id
WHERE ar.reviewer_id = $1
ORDER BY pr.created_at DESC
`

type ListPullRequestsByReviewerRow struct {
	PullRequestID   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
	AuthorID        string `json:"author_id"`
	Status          string `json:"status"`
}

func (q *Queries) ListPullRequestsByReviewer(ctx context.Context, reviewerID string) ([]ListPullRequestsByReviewerRow, error) {
	rows, err := q.db.Query(ctx, listPullRequestsByReviewer, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPullRequestsByReviewerRow{}
	for rows.Next() {
		var i ListPullRequestsByReviewerRow
		if err := rows.Scan(
			&i.PullRequestID,
			&i.PullRequestName,
			&i.AuthorID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergePullRequest = `-- name: MergePullRequest :one
UPDATE pull_requests
SET status = 'MERGED', 
    merged_at = COALESCE(merged_at, NOW())
WHERE pull_request_id = $1
RETURNING pull_request_id, pull_request_name, author_id, status, created_at, merged_at
`

func (q *Queries) MergePullRequest(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRow(ctx, mergePullRequest, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const pRExists = `-- name: PRExists :one
SELECT EXISTS(SELECT 1 FROM pull_requests WHERE pull_request_id = $1)
`

func (q *Queries) PRExists(ctx context.Context, pullRequestID string) (bool, error) {
	row := q.db.QueryRow(ctx, pRExists, pullRequestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
