// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddReviewer(ctx context.Context, arg AddReviewerParams) error
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error)
	CreateTeam(ctx context.Context, teamName string) (string, error)
	GetActiveCandidatesForPR(ctx context.Context, arg GetActiveCandidatesForPRParams) ([]GetActiveCandidatesForPRRow, error)
	GetActiveCandidatesForReassignment(ctx context.Context, arg GetActiveCandidatesForReassignmentParams) ([]string, error)
	GetAssignedReviewers(ctx context.Context, prID string) ([]string, error)
	GetPRAuthorId(ctx context.Context, pullRequestID string) (string, error)
	GetPRStats(ctx context.Context) (GetPRStatsRow, error)
	GetPullRequest(ctx context.Context, pullRequestID string) (PullRequest, error)
	GetReviewerWorkload(ctx context.Context) ([]GetReviewerWorkloadRow, error)
	GetTeam(ctx context.Context, teamName string) (string, error)
	GetUser(ctx context.Context, userID string) (User, error)
	GetUserAssignmentStats(ctx context.Context) ([]GetUserAssignmentStatsRow, error)
	GetUsersByTeam(ctx context.Context, teamName string) ([]User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	IsReviewerAssigned(ctx context.Context, arg IsReviewerAssignedParams) (bool, error)
	ListPullRequestsByReviewer(ctx context.Context, reviewerID string) ([]ListPullRequestsByReviewerRow, error)
	MergePullRequest(ctx context.Context, pullRequestID string) (PullRequest, error)
	PRExists(ctx context.Context, pullRequestID string) (bool, error)
	RemoveReviewer(ctx context.Context, arg RemoveReviewerParams) error
	ReplaceReviewer(ctx context.Context, arg ReplaceReviewerParams) error
	SetUserActivity(ctx context.Context, arg SetUserActivityParams) (User, error)
	TeamExists(ctx context.Context, teamName string) (bool, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UserExists(ctx context.Context, userID string) (bool, error)
}

var _ Querier = (*Queries)(nil)
