// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviewers.sql

package sqlc

import (
	"context"
)

const addReviewer = `-- name: AddReviewer :exec
INSERT INTO assigned_reviewers (pr_id, reviewer_id)
VALUES ($1, $2)
`

type AddReviewerParams struct {
	PrID       string `json:"pr_id"`
	ReviewerID string `json:"reviewer_id"`
}

func (q *Queries) AddReviewer(ctx context.Context, arg AddReviewerParams) error {
	_, err := q.db.Exec(ctx, addReviewer, arg.PrID, arg.ReviewerID)
	return err
}

const getAssignedReviewers = `-- name: GetAssignedReviewers :many
SELECT reviewer_id
FROM assigned_reviewers
WHERE pr_id = $1
ORDER BY reviewer_id
`

func (q *Queries) GetAssignedReviewers(ctx context.Context, prID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAssignedReviewers, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var reviewer_id string
		if err := rows.Scan(&reviewer_id); err != nil {
			return nil, err
		}
		items = append(items, reviewer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isReviewerAssigned = `-- name: IsReviewerAssigned :one
SELECT EXISTS (
  SELECT 1
  FROM assigned_reviewers
  WHERE pr_id = $1 AND reviewer_id = $2
) AS is_assigned
`

type IsReviewerAssignedParams struct {
	PrID       string `json:"pr_id"`
	ReviewerID string `json:"reviewer_id"`
}

func (q *Queries) IsReviewerAssigned(ctx context.Context, arg IsReviewerAssignedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isReviewerAssigned, arg.PrID, arg.ReviewerID)
	var is_assigned bool
	err := row.Scan(&is_assigned)
	return is_assigned, err
}

const removeReviewer = `-- name: RemoveReviewer :exec
DELETE FROM assigned_reviewers
WHERE pr_id = $1 AND reviewer_id = $2
`

type RemoveReviewerParams struct {
	PrID       string `json:"pr_id"`
	ReviewerID string `json:"reviewer_id"`
}

func (q *Queries) RemoveReviewer(ctx context.Context, arg RemoveReviewerParams) error {
	_, err := q.db.Exec(ctx, removeReviewer, arg.PrID, arg.ReviewerID)
	return err
}

const replaceReviewer = `-- name: ReplaceReviewer :exec
UPDATE assigned_reviewers
SET reviewer_id = $3
WHERE pr_id = $1 AND reviewer_id = $2
`

type ReplaceReviewerParams struct {
	PrID         string `json:"pr_id"`
	ReviewerID   string `json:"reviewer_id"`
	ReviewerID_2 string `json:"reviewer_id_2"`
}

func (q *Queries) ReplaceReviewer(ctx context.Context, arg ReplaceReviewerParams) error {
	_, err := q.db.Exec(ctx, replaceReviewer, arg.PrID, arg.ReviewerID, arg.ReviewerID_2)
	return err
}
