// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"
)

const getPRStats = `-- name: GetPRStats :one
SELECT 
    COUNT(*) as total_prs,
    COUNT(*) FILTER (WHERE status = 'OPEN') as open_prs,
    COUNT(*) FILTER (WHERE status = 'MERGED') as merged_prs
FROM pull_requests
`

type GetPRStatsRow struct {
	TotalPrs  int64 `json:"total_prs"`
	OpenPrs   int64 `json:"open_prs"`
	MergedPrs int64 `json:"merged_prs"`
}

func (q *Queries) GetPRStats(ctx context.Context) (GetPRStatsRow, error) {
	row := q.db.QueryRow(ctx, getPRStats)
	var i GetPRStatsRow
	err := row.Scan(&i.TotalPrs, &i.OpenPrs, &i.MergedPrs)
	return i, err
}

const getReviewerWorkload = `-- name: GetReviewerWorkload :many
SELECT 
    u.user_id,
    u.username,
    u.team_name,
    COUNT(ar.pr_id) as open_prs_count
FROM users u
LEFT JOIN assigned_reviewers ar ON u.user_id = ar.reviewer_id
LEFT JOIN pull_requests pr ON ar.pr_id = pr.pull_request_id AND pr.status = 'OPEN'
WHERE u.is_active = true
GROUP BY u.user_id, u.username, u.team_name
ORDER BY open_prs_count DESC
`

type GetReviewerWorkloadRow struct {
	UserID       string `json:"user_id"`
	Username     string `json:"username"`
	TeamName     string `json:"team_name"`
	OpenPrsCount int64  `json:"open_prs_count"`
}

func (q *Queries) GetReviewerWorkload(ctx context.Context) ([]GetReviewerWorkloadRow, error) {
	rows, err := q.db.Query(ctx, getReviewerWorkload)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewerWorkloadRow{}
	for rows.Next() {
		var i GetReviewerWorkloadRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TeamName,
			&i.OpenPrsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAssignmentStats = `-- name: GetUserAssignmentStats :many
SELECT 
    u.user_id,
    u.username,
    u.team_name,
    COUNT(ar.pr_id) as assignments_count
FROM users u
LEFT JOIN assigned_reviewers ar ON u.user_id = ar.reviewer_id
GROUP BY u.user_id, u.username, u.team_name
ORDER BY assignments_count DESC, u.user_id
`

type GetUserAssignmentStatsRow struct {
	UserID           string `json:"user_id"`
	Username         string `json:"username"`
	TeamName         string `json:"team_name"`
	AssignmentsCount int64  `json:"assignments_count"`
}

func (q *Queries) GetUserAssignmentStats(ctx context.Context) ([]GetUserAssignmentStatsRow, error) {
	rows, err := q.db.Query(ctx, getUserAssignmentStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAssignmentStatsRow{}
	for rows.Next() {
		var i GetUserAssignmentStatsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TeamName,
			&i.AssignmentsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
