// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (team_name)
VALUES ($1)
RETURNING team_name
`

func (q *Queries) CreateTeam(ctx context.Context, teamName string) (string, error) {
	row := q.db.QueryRow(ctx, createTeam, teamName)
	var team_name string
	err := row.Scan(&team_name)
	return team_name, err
}

const getTeam = `-- name: GetTeam :one
SELECT team_name
FROM teams
WHERE team_name = $1
`

func (q *Queries) GetTeam(ctx context.Context, teamName string) (string, error) {
	row := q.db.QueryRow(ctx, getTeam, teamName)
	var team_name string
	err := row.Scan(&team_name)
	return team_name, err
}

const teamExists = `-- name: TeamExists :one
SELECT EXISTS(SELECT 1 FROM teams WHERE team_name = $1)
`

func (q *Queries) TeamExists(ctx context.Context, teamName string) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, teamName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
