// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const getActiveCandidatesForPR = `-- name: GetActiveCandidatesForPR :many
SELECT user_id, username
FROM users
WHERE team_name = $1 
  AND is_active = true 
  AND user_id != $2
ORDER BY RANDOM()
LIMIT 2
`

type GetActiveCandidatesForPRParams struct {
	TeamName string `json:"team_name"`
	UserID   string `json:"user_id"`
}

type GetActiveCandidatesForPRRow struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) GetActiveCandidatesForPR(ctx context.Context, arg GetActiveCandidatesForPRParams) ([]GetActiveCandidatesForPRRow, error) {
	rows, err := q.db.Query(ctx, getActiveCandidatesForPR, arg.TeamName, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveCandidatesForPRRow{}
	for rows.Next() {
		var i GetActiveCandidatesForPRRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveCandidatesForReassignment = `-- name: GetActiveCandidatesForReassignment :many
SELECT user_id
FROM users
WHERE team_name = $1 
  AND is_active = true 
  AND user_id != $2
  AND user_id NOT IN (
    SELECT reviewer_id 
    FROM assigned_reviewers 
    WHERE pr_id = $3
  )
ORDER BY RANDOM()
LIMIT 1
`

type GetActiveCandidatesForReassignmentParams struct {
	TeamName string `json:"team_name"`
	UserID   string `json:"user_id"`
	PrID     string `json:"pr_id"`
}

func (q *Queries) GetActiveCandidatesForReassignment(ctx context.Context, arg GetActiveCandidatesForReassignmentParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getActiveCandidatesForReassignment, arg.TeamName, arg.UserID, arg.PrID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, team_name, is_active
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const getUsersByTeam = `-- name: GetUsersByTeam :many
SELECT user_id, username, team_name, is_active
FROM users
WHERE team_name = $1
ORDER BY user_id
`

func (q *Queries) GetUsersByTeam(ctx context.Context, teamName string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByTeam, teamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TeamName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (user_id, username, team_name, is_active)
VALUES ($1, $2, $3, $4)
RETURNING user_id, username, team_name, is_active
`

type InsertUserParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	TeamName string `json:"team_name"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.UserID,
		arg.Username,
		arg.TeamName,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const setUserActivity = `-- name: SetUserActivity :one
UPDATE users
SET is_active = $2
WHERE user_id = $1
RETURNING user_id, username, team_name, is_active
`

type SetUserActivityParams struct {
	UserID   string `json:"user_id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) SetUserActivity(ctx context.Context, arg SetUserActivityParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActivity, arg.UserID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    username = $2,
    team_name = $3,
    is_active = $4
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	TeamName string `json:"team_name"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.TeamName,
		arg.IsActive,
	)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE user_id = $1)
`

func (q *Queries) UserExists(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
